<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
                <?php echo (isset($this->alert) ? $this->alert :''); ?>
                <form action="<?php echo BASE; ?>cadastro/cadastrar/" class="form-horizontal"  method="post">
                  <div class="form-group">
                    <label for="name" class="col-sm-3 control-label">Nome:</label>
                    <div class="col-sm-8">
                      <input required="true" type="text" class="form-control" name="name" id="name" placeholder="Nome Completo">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="text" class="col-sm-3 control-label">E-mail:</label>
                    <div class="col-sm-8">
                      <input required="true"  type="text" class="form-control" name="email" id="email" placeholder="seuemail@site.com.br">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="username" class="col-sm-3 control-label">Usuario:</label>
                    <div class="col-sm-8">
                      <input required="true" type="text" class="form-control" name="username" id="username" placeholder="Seuusername">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="password" class="col-sm-3 control-label">Senha:</label>
                    <div class="col-sm-8">
                      <input required="true" type="password" class="form-control" name="password" id="password" placeholder="Suasenha">
                    </div>
                  </div>
                  
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div>
                  </div>
                </form>
            </div>
        </div>
    </div>
</div>